title: Tok&Go documentation
description: This page is ment to store technical documentation of the tockandgo product.
theme: just-the-docs

url: https://alegria20.github.io

aux_links:
  Template Repository: https://www.tokandgo.com/
